# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrndj', '0004_auto_20161205_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
